# Generated by Django 5.2.8 on 2025-11-17 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'tipo_utilizador': 'vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL),
        ),
    ]
